### ISSUE TITLE
Set color and size of projectiles to match their owners

### ISSUE THREAD

**Issue by nashkevin** [nashkevin/EECS-393-Project#12]
It would be nice if rather than having a uniform size and color, projectiles were scaled and colored to match their owners.

**Comment by nerdydrew** [comment]
Projectiles can be different sizes as of commit bbca5c6e4ddf7a38080c23d5a2e0aeaa26f2edbe. Projectiles can be different colors as of commit f52a46b3408d0686155add8513d3b78a499f4b0a.
