### ISSUE TITLE
NPCAgents don't move or change targets when necessary

### ISSUE THREAD

**Issue by nashkevin** [nashkevin/EECS-393-Project#13]

**Comment by kevinwang95** [comment]
This is fixed as of commit 064bd27.

After each firing of the projectile, the agent will set the current target to null, and thus looks again for the next target. This then ensures that after an enemy dies, and if there is a nearby enemy, the NPC agent will relook for another target and find the nearby enemy.

**Comment by nashkevin** [comment]
I don't like the fix in 064bd2710385f11258ae558fdb576a2ccfa6cd8f as it's more of a workaround. NPCs should target the same player until it's no longer appropriate (i.e. the target has despawned or moved out of range). This workaround forces the NPC to forget its target and find a new one with every single update, which is more expensive than retaining one. It also causes the side effect of NPCs targeting the nearest individual at any given time, rather than sticking with the same target as I intended for them to do.

**Comment by nashkevin** [comment]
Regardless, it seems this bug is actually two bugs, which I categorized as one because I (lazily) didn't want to dig deeper at the time. Even if we accept this solution, NPCs don't currently move, so I'll close this and split it into two separate issues.
