### ISSUE TITLE
Where's the edge of the arena?

### ISSUE THREAD

**Issue by Jidek** [nashkevin/EECS-393-Project#16]
We should make some visual indicator of the edge of the arena. Because players are spawned near the edge they should see it upon spawning.

**Comment by nerdydrew** [comment]
Implemented in commits 00a96b2d81cd49bf66b703ec0acf74a9f4e513ea , bdf82a34abc23a138ac7a454d28ca69c0999dd6e, and e3ed28c87c7275048575b444aa35a8bb39bb5a0d.
