### ISSUE TITLE
Enforce environment boundaries on the back end

### ISSUE THREAD

**Issue by nerdydrew** [nashkevin/EECS-393-Project#17]
Currently, there is nothing preventing players and NPCs from going beyond the radius of the environment. This can happen either through moving normally or with the `/goto` command. This boundary check should probably be implemented in the move methods for agents.

**Comment by kevinwang95** [comment]
Let me take care of this issue.

**Comment by nashkevin** [comment]
Seems to be completely functional as of cb4ebbf40f132ea5d3c5a002d1347db15fe4d9e8.
