### ISSUE TITLE
PlayerAgents don't always move in cardinal directions

### ISSUE THREAD

**Issue by nashkevin** [nashkevin/EECS-393-Project#20]
For example, rather than traveling directly upward when the up arrow key is held, the PlayerAgent moves mostly upward, but with a slight tilt to the right.

https://gfycat.com/SelfishMediumEmu

This bug has been kicking around for a while now, but either nobody else has noticed it or nobody has bothered to open an issue for it.

**Comment by nerdydrew** [comment]
I have noticed this as well, but I can't reproduce it / figure out the cause.

**Comment by Jidek** [comment]
I definitely saw this bug a while ago, but I can't reproduce it anymore. Maybe it was fixed by something else accidentally?

**Comment by nashkevin** [comment]
Closing the issue, since this bug hasn't been observed in over two weeks.
