### ISSUE TITLE
Set player agents to different teams

### ISSUE THREAD

**Issue by nerdydrew** [nashkevin/EECS-393-Project#21]
Currently, all player agents are set to the Agent.Team.RED team, which means no player vs. player combat can happen. 

Proposed functionality: whenever a player joins, they should be assigned to whichever team has fewer people, or a randomly if it's a tie. This would require the environment to keep track of (or calculate) the team balance. There could be a method called `getSmallestTeam()` that returns the team with the fewest number of players.

**Comment by Jidek** [comment]
I'll set up the environment to keep track of teams

**Comment by nashkevin** [comment]
The `/team` command can set this explicitly, though I haven't changed Environment to handle it.

**Comment by Jidek** [comment]
The environment now randomly places player agents into teams when spawning and keeps track of teams using sets. There should be a change to add players to their team list whenever team is changed through any external means like `/team`. This can easily be done by calling `environment.removePlayerFromTeam(player)` before changing their team and `environment.addPlayerToTeam(player)` after changing their team as these methods will check the team before adding/removing them from the appropriate list.

**Comment by nashkevin** [comment]
Full functional as of d02f4a0d7889901bd338ab3305ae8a5da1120612
