### ISSUE TITLE
Recolor players to match their team

### ISSUE THREAD

**Issue by nashkevin** [nashkevin/EECS-393-Project#23]
Currently players don't change color based on their team, though their projectiles do. Players with no team should stay the green color that we currently use.

**Comment by Jidek** [comment]
Maybe this issue just wasn't updated, but it looks like players colors are changing to match their team appropriately.

**Comment by nashkevin** [comment]
The initial color is correct. When a team change occurs, the projectiles are updated but the bodies are not.

**Comment by nerdydrew** [comment]
Fixed this with commit b7ee3b3444f0c5af6f4354057c245585671e19c9. Unfortunately, I can't find any way to check what color the sprite currently is, so I need to redraw the sprite texture each frame.
