### ISSUE TITLE
When an enemy is defeated the health bar graphic sometimes glitches out

### ISSUE THREAD

**Issue by Jidek** [nashkevin/EECS-393-Project#25]
Sometimes when an enemy is defeated, as well as their health bar turning from green to red, the entire horizontal axis to the left of the health bar becomes green.

**Comment by Jidek** [comment]
I think this might be a result of negative health. If this is the case, for an indeterminate number of frames, the health is represented as a negative health bar before the kill message is sent to remove the NPC

**Comment by nerdydrew** [comment]
I just added a check that prevents health from going negative in commit c2ea5112cdf3da481b14cc9932aded873d2e6a21. It seems to work for me, but you should test it more to be sure.

**Comment by nashkevin** [comment]
Spawned 500 scouts. Killed 500 scouts. No glitches.
