### ISSUE TITLE
/stats command no longer works

### ISSUE THREAD

**Issue by nashkevin** [nashkevin/EECS-393-Project#26]
Any use of `/stats` or any of its aliases displays the help text for the command, rather than the stats of the Player.

**Comment by nashkevin** [comment]
as of 042ab1ecb758fc1e038770bbd0a4b553053d2fd3, it seems.

**Comment by nerdydrew** [comment]
Fixed in commit 4edde94a799da857a9ca701cd3eb5b0154bcea23.
