### ISSUE TITLE
Players move extremely fast

### ISSUE THREAD

**Issue by nashkevin** [nashkevin/EECS-393-Project#8]
```
Kevin: /goto 0 0
Kevin: /where
(0.0, 0.0)
```
[a mere second or two of holding down the D key]
```
Kevin: /where
(1.1452527E7, 0.0)
```

**Comment by nashkevin** [comment]
Bug originated in commit 3ac73843b827b6a9f901e021add44c7469d1ee5c

**Comment by kevinwang95** [comment]
Yes, I see. If we are doing acceleration vectors, then that piece of code is necessary so that the vector does not become 0 when there is no input. Without it, it is essentially just a position vector that moves.

However, it looks like our speed isn't capped, we can make those changes.
